AWSTemplateFormatVersion: '2010-09-09'
Description: A simple backend with a RESTful API endpoint using Amazon API Gateway.
Resources:
  dbManagerService:
    Properties:
      CodeUri: s3://rahzel-package/d0cf692ce3044419ba311e4365ebc1b4
      Description: A simple backend with a RESTful API endpoint using Amazon API Gateway.
      Events:
        Api1:
          Properties:
            Method: POST
            Path: /api
          Type: Api
        Api2:
          Properties:
            Method: ANY
            Path: /api/{itemId}
          Type: Api
      Handler: handler.dbManagerLambda
      MemorySize: 512
      Policies:
      - Statement:
        - Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/myItems
        Version: '2012-10-17'
      Runtime: nodejs8.10
      Timeout: 10
    Type: AWS::Serverless::Function
  myItems:
    Properties:
      AttributeDefinitions:
      - AttributeName: itemId
        AttributeType: S
      KeySchema:
      - AttributeName: itemId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: myItems
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
