AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple backend with a RESTful API endpoint using Amazon API Gateway.

Globals:
  Function:
    MemorySize: 512
    Timeout: 10
    Runtime: nodejs8.10

Outputs:
  Api:
    Description: url endpoint to test stack
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/items/

Resources:
  dbManagerService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.itemHandler
      CodeUri: ./dist
      Description: A simple backend with a RESTful API endpoint using Amazon API Gateway.
      Events:
        Api1:
          Properties:
            Method: POST
            Path: /items
          Type: Api
        Api2:
          Properties:
            Method: ANY
            Path: /items/{id}
          Type: Api
      
      Policies:
      - Statement:
        - Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/myItems
        Version: '2012-10-17'
    
  myItems:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: item_id
        AttributeType: S
      KeySchema:
      - AttributeName: item_id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: myItems